### ISSUE TITLE
Flag to output factorization

### ISSUE THREAD

**Issue by albertiniufu** [felipelouza/lyndon-array#1]
Hi, 
I think it would be useful to have a flag to output the lyndon factorization produced.

Best,

**Comment by felipelouza** [comment]
Do you mean the factors (substrings), one by line? It can be very large, don't you think?

**Comment by albertiniufu** [comment]
Yes, but for debugging purposes it can be useful.

**Comment by felipelouza** [comment]
Done!
Added option -L, then it outputs the lyndon-factors on INPUT.lyn

Thanks!
